# Generated by Django 4.2.13 on 2024-06-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortafolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
