# Generated by Django 4.2.13 on 2024-06-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortafolioApp', '0002_remove_noticia_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
        ),
    ]
