# Generated by Django 4.0.4 on 2024-06-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_resultadoencuesta_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoencuesta',
            name='imagen_respuesta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_respuestas/'),
        ),
    ]
