# Generated by Django 4.0.4 on 2024-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_resultadoencuesta_imagen_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_imagenes/')),
            ],
        ),
    ]
